<?php

//importo le librerie fondamentali
function load_node_ajax_init(){
	drupal_add_library('system', 'ui.dialog');
	drupal_add_library('system', 'drupal.ajax');
}

/*
 * Implements hook_menu()
 */
function load_node_ajax_menu(){
	$items = array();
	
	$items['ajax-product'] = array(
		'page callback' => 'load_node_ajax_link_response',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function load_node_ajax_link_response($type = 'ajax', $container, $nid = 0){
	$output = _load_node_ajax_node_loader($nid);
	if($type == 'ajax'){
		$commands = array();
		/*
		 * argomento 1: contenitore da sostituire
		 * argomento 2: contenitore + nuovi dati
		 */
		$commands[] = ajax_command_replace('#'.$container, '<div id="'.$container.'" class="overlay-dialog">'.$output.'</div>');
		$page = array(
			'#type' => 'ajax',
			'#commands' => $commands,
		);
		ajax_deliver($page);
	}
	//in caso non sia settato su ajax ritorno i dati normalmente
	else{
		$output = "<div id='".$container."'>".$output.'</div>';
		return $output;
	}
}

function _load_node_ajax_node_loader($nid = 0){
	$node = node_load($nid, NULL, false);
	if($node){
		return render(node_view($node, 'full'));
	}
}
